name: Publish JS Client to NPM

on:
  push:
    branches: [ "main" ]
    paths:
      - 'clients/js/pgrest-client.js'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: ./clients/js
        run: npm install

      - name: Publish to NPM
        working-directory: ./clients/js
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}